# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savestring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveString', to=settings.AUTH_USER_MODEL),
        ),
    ]
